import { JavaClass, ComponentType, DependencyReference, RelationshipType } from "../common/types";
import { IGNORED_JAVA_TYPES, ORM_FIELD_ANNOTATIONS } from "../common/constants";

/**
 * SemanticExtractor traverses the AST generated by JavaParser and extracts
 * structured class metadata (package, imports, class name, annotations, dependencies).
 * Every extracted dependency carries a RelationshipType indicating the semantic nature
 * of the relationship: DEPENDENCY, INHERITANCE, or ORM_RELATIONSHIP.
 */
export class SemanticExtractor {
  private packageName = "";
  private imports: string[] = [];
  private className = "";
  private type: ComponentType = "CLASS";
  private baseTypes: string[] = [];
  private dependenciesList: DependencyReference[] = [];

  /**
   * Extracts class metadata from the Java AST.
   * @param ast The AST returned by JavaParser.
   * @param filePath The absolute file path of the source code.
   * @returns Extracted JavaClass.
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/explicit-module-boundary-types
  public extract(ast: any, filePath: string): JavaClass {
    if (!ast) {
      return this.emptyMetadata(filePath);
    }

    this.resetState();
    this.walk(ast, filePath);

    const fqName = this.packageName ? `${this.packageName}.${this.className}` : this.className;

    // Filter duplicates and self-references, preserving relationship type
    const uniqueDependencies: DependencyReference[] = [];
    const seen = new Set<string>();
    for (const dep of this.dependenciesList) {
      if (dep.className !== this.className && !seen.has(dep.className)) {
        seen.add(dep.className);
        uniqueDependencies.push(dep);
      }
    }

    return {
      filePath,
      packageName: this.packageName,
      className: this.className,
      fullyQualifiedName: fqName,
      type: this.type,
      baseTypes: [...this.baseTypes],
      dependencies: uniqueDependencies,
      imports: [...this.imports],
    };
  }

  private resetState(): void {
    this.packageName = "";
    this.imports = [];
    this.className = "";
    this.type = "CLASS";
    this.baseTypes = [];
    this.dependenciesList = [];
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  private walk(node: any, filePath: string): void {
    if (!node) {
      return;
    }

    if (node.name === "packageDeclaration") {
      this.packageName = this.findIdentifiers(node).join(".");
      return;
    }

    if (node.name === "importDeclaration") {
      const importParts = this.findIdentifiers(node);
      if (importParts.length > 0) {
        this.imports.push(importParts.join("."));
      }
      return;
    }

    if (
      node.name === "normalClassDeclaration" ||
      node.name === "normalInterfaceDeclaration" ||
      node.name === "recordDeclaration" ||
      node.name === "enumDeclaration"
    ) {
      const typeIdentifierNode = node.children?.typeIdentifier?.[0];
      if (typeIdentifierNode) {
        const names = this.findIdentifiers(typeIdentifierNode);
        if (names.length > 0) {
          this.className = names[0];
        }
      }

      // Extract extends/implements/interfaceExtends as INHERITANCE relationships,
      // skipping body declarations (classBody, interfaceBody, etc.)
      for (const key of Object.keys(node.children || {})) {
        if (key !== "classBody" && key !== "interfaceBody" && key !== "recordBody" && key !== "enumBody") {
          const isInheritanceKey =
            key === "classExtends" || key === "classImplements" || key === "interfaceExtends";
          for (const child of node.children[key]) {
            const tokens = this.findIdentifierTokens(child);
            for (const token of tokens) {
              if (this.isValidDependency(token.image)) {
                if (isInheritanceKey) {
                  this.baseTypes.push(token.image);
                  this.dependenciesList.push({
                    className: token.image,
                    relationshipType: RelationshipType.INHERITANCE,
                    location: { filePath, line: token.line, column: token.column },
                  });
                } else {
                  // Type parameters and other non-body, non-inheritance keys remain DEPENDENCY
                  this.dependenciesList.push({
                    className: token.image,
                    relationshipType: RelationshipType.DEPENDENCY,
                    location: { filePath, line: token.line, column: token.column },
                  });
                }
              }
            }
          }
        }
      }
    }

    if (node.name === "classModifier" || node.name === "interfaceModifier") {
      const annotationNode = node.children?.annotation?.[0];
      if (annotationNode) {
        const annotationName = this.findIdentifiers(annotationNode.children?.typeName?.[0]).join(".");
        if (
          annotationName === "RestController" ||
          annotationName === "Controller" ||
          annotationName === "ControllerAdvice" ||
          annotationName === "RestControllerAdvice"
        ) {
          this.type = "CONTROLLER";
        } else if (annotationName === "Service") {
          this.type = "SERVICE";
        } else if (annotationName === "Repository") {
          this.type = "REPOSITORY";
        } else if (
          annotationName === "Entity" ||
          annotationName === "MappedSuperclass" ||
          annotationName === "Embeddable"
        ) {
          this.type = "ENTITY";
        }
      }
    }

    if (node.name === "fieldDeclaration") {
      // Determine whether this field has an ORM annotation by inspecting fieldModifier children
      const isOrmField = this.hasOrmAnnotation(node);
      const relType = isOrmField ? RelationshipType.ORM_RELATIONSHIP : RelationshipType.DEPENDENCY;

      const unannTypeNode = node.children?.unannType?.[0];
      if (unannTypeNode) {
        const fieldTokens = this.findIdentifierTokens(unannTypeNode);
        for (const token of fieldTokens) {
          if (this.isValidDependency(token.image)) {
            this.dependenciesList.push({
              className: token.image,
              relationshipType: relType,
              location: { filePath, line: token.line, column: token.column },
            });
          }
        }
      }
    }

    if (node.name === "formalParameter") {
      // Constructor and method parameters are always direct DEPENDENCY relationships
      const paramTypeNode = node.children?.variableParaRegularParameter?.[0]?.children?.unannType?.[0];
      if (paramTypeNode) {
        const paramTokens = this.findIdentifierTokens(paramTypeNode);
        for (const token of paramTokens) {
          if (this.isValidDependency(token.image)) {
            this.dependenciesList.push({
              className: token.image,
              relationshipType: RelationshipType.DEPENDENCY,
              location: { filePath, line: token.line, column: token.column },
            });
          }
        }
      }
    }

    if (node.children) {
      for (const key of Object.keys(node.children)) {
        for (const child of node.children[key]) {
          this.walk(child, filePath);
        }
      }
    }
  }

  /**
   * Checks whether a fieldDeclaration node has any ORM-related field modifier annotations.
   * Inspects all fieldModifier children for annotations matching ORM_FIELD_ANNOTATIONS.
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  private hasOrmAnnotation(fieldDeclarationNode: any): boolean {
    const modifiers = fieldDeclarationNode.children?.fieldModifier ?? [];
    for (const modifier of modifiers) {
      const annotationNode = modifier.children?.annotation?.[0];
      if (annotationNode) {
        const annotName = this.findIdentifiers(annotationNode.children?.typeName?.[0]).join(".");
        if (ORM_FIELD_ANNOTATIONS.has(annotName)) {
          return true;
        }
      }
    }
    return false;
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  private findIdentifiers(node: any): string[] {
    return this.findIdentifierTokens(node).map((t) => t.image);
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  private findIdentifierTokens(node: any): { image: string; line: number; column: number }[] {
    const tokens: { image: string; line: number; column: number }[] = [];
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const traverse = (n: any) => {
      if (!n) {
        return;
      }
      if (n.image && n.tokenType?.name === "Identifier") {
        tokens.push({
          image: n.image,
          line: n.startLine ?? 1,
          column: n.startColumn ?? 1,
        });
      }
      if (n.children) {
        for (const key of Object.keys(n.children)) {
          for (const child of n.children[key]) {
            traverse(child);
          }
        }
      }
    };
    traverse(node);
    return tokens;
  }

  private isValidDependency(type: string): boolean {
    return !IGNORED_JAVA_TYPES.has(type) && /^[A-Z]/.test(type);
  }

  private emptyMetadata(filePath: string): JavaClass {
    return {
      filePath,
      packageName: "",
      className: "",
      fullyQualifiedName: "",
      type: "CLASS",
      baseTypes: [],
      dependencies: [],
      imports: [],
    };
  }
}
